id:                 "testing"
short:              "testing"
language:           sk
full:
    nominative:     "Testovací seminár pre DeGeŠ"
    genitive:       "Testovacieho seminára pre DeGeŠ"
    locative:       "Testovacom seminári pre DeGeŠ"
head:
    name:           "Testovač"
    email:          "test@test.test"
    phone:          "+421 918 918 918"
founded:            2023
urls:
    web:            "https://github.com/trojsten/dgs/"
    submit:         "https://github.com/trojsten/dgs/wiki/"
email:              "none@none.no"
organisation:
    department:
        short:      "DeGeŠ"
        full:       "Oddelenie testovania"
    faculty:
        short:      "FMFI UK"
        full:       "Fakulta matematiky, fyziky a informatiky"
    address:        "Mlynská dolina, 842 48 Bratislava"

categories:         [[], [], [], [], [], []]

hacks:
    smallLogoRaise: "-2pt"
