id:                 "testing"
short:              "testing"
language:           en
full:
    nominative:     "DeGeŠ testing seminar"
    genitive:       "DeGeŠ testing seminar"
    locative:       "DeGeŠ testing seminar"
head:
    name:           "Master Tester"
    email:          "test@test.test"
    phone:          "+421 918 918 918"
founded:            2023
urls:
    web:            "https://github.com/trojsten/dgs/"
    submit:         "https://github.com/trojsten/dgs/wiki/"
email:              "none@none.no"
organisation:
    department:
        short:      "DeGeŠ"
        full:       "department of testing"
    faculty:
        short:      "FoT"
        full:       "faculty of typography"
    address:        "Owners' club"

categories:         [[], [], [], [], [], []]

hacks:
    smallLogoRaise: "-2pt"
